### PR TITLE
Modified Sounds

### PR DESCRIPTION
**Pull request by LemonDrop847**
Modified Button Click, Error sounds, Added a different sound on login.
Please merge whichever is appropriate.

### CODE REVIEW

**Comment by codeboyfriend** [comment]
Do you add new sound file or you used the current one

**Comment by LemonDrop847** [comment]
> Do you add new sound file or you used the current one

added a new one

**Comment by codeboyfriend** [comment]
Star the repo nd or will be merge

**Comment by LemonDrop847** [comment]
Starred!

**Pull request merged**
